const previewContract = [
  {
    hasBasicColumn: true,
    hasMekifColumn: true,
    hasCustomColumn: true,
    hasMeetingColumn: true,
    numOfPagesBasic: '3',
    wordFileBasic: false,
    tailoredBasic: false,
    numOfFixesBasic: '0',
    makingTimeBasic: '0',
    levelOfProtectionBasic: '2',
    warrantyBasic: false,
    numOfPagesMekif: '12',
    wordFileMekif: true,
    tailoredMekif: false,
    numOfFixesMekif: '0',
    makingTimeMekif: '0',
    levelOfProtectionMekif: '3',
    warrantyMekif: false,
    priceMekif: '220',
    numOfPagesCustom: '13',
    wordFileCustom: true,
    tailoredCustom: true,
    numOfFixesCustom: '1',
    makingTimeCustom: '2',
    levelOfProtectionCustom: '4',
    warrantyCustom: false,
    priceCustom: '720',
    numOfPagesMeeting: '0',
    wordFileMeeting: true,
    tailoredMeeting: true,
    numOfFixesMeeting: '2',
    makingTimeMeeting: '7',
    levelOfProtectionMeeting: '5',
    warrantyMeeting: true,
    priceMeeting: '1320',
    imgSrc: '../assets/img/contracts/הסכם גירושין.jpg',
    buttonText: 'פתח עוד',
    href: 'contract/1',
    h1: 'הסכם גירושין',
    tags: ['הסכם גירושין', 'הסכם גירושין בהסכמה', 'עורך דין הסכם גירושין', 'הסכם גירושין לדוגמא'],

    seoHeader: `הסכם גירושין לדוגמא - הסכם גירושין לרכישה און ליין שירות חדש  / עו"ד אלעד כהן
`,
    seoDescription: `הסכם גירושין - שאלות ותשובות בנושא הסכם גירושין - רכישת הסכם גירושין מקיף און ליין במהירות ובפשטות. עורך דין הסכם גירושין אלעד כהן.`,

    categoryHeb: 'משפחה',
    id: '1',
    price: 85,
    title: `הסכם גירושין`,
  },
  {
    hasBasicColumn: true,
    hasMekifColumn: true,
    hasCustomColumn: true,
    hasMeetingColumn: true,

    numOfPagesBasic: '4',
    wordFileBasic: false,
    tailoredBasic: false,
    numOfFixesBasic: '0',
    makingTimeBasic: '0',
    levelOfProtectionBasic: '2',
    warrantyBasic: false,
    numOfPagesMekif: '11',
    wordFileMekif: true,
    tailoredMekif: false,
    numOfFixesMekif: '0',
    makingTimeMekif: '0',
    levelOfProtectionMekif: '3',
    warrantyMekif: false,
    priceMekif: '220',
    numOfPagesCustom: '12',
    wordFileCustom: true,
    tailoredCustom: true,
    numOfFixesCustom: '1',
    makingTimeCustom: '2',
    levelOfProtectionCustom: '4',
    warrantyCustom: false,
    priceCustom: '720',
    numOfPagesMeeting: '0',
    wordFileMeeting: true,
    tailoredMeeting: true,
    numOfFixesMeeting: '2',
    makingTimeMeeting: '7',
    levelOfProtectionMeeting: '5',
    warrantyMeeting: true,
    priceMeeting: '1320',
    imgSrc: '../assets/img/contracts/הסכם הורות משותפת.jpg',
    buttonText: 'פתח עוד',
    href: 'contract/2',

    h1: 'הסכם הורות משותפת',
    tags: ['הסכם הורות משותפת', 'הסכם הורות משותפת להפריה', 'נוסח הסכם הורות משותפת', 'הורות משותפת'],

    seoHeader: `הסכם הורות משותפת לדוגמא - הסכם לרכישה און ליין שירות חדש / עו"ד אלעד כהן
    `,
    seoDescription: `הסכם הורות משותפת - שאלות ותשובות בנושא הסכם הורות משותפת - רכישת הסכם מקיף און ליין במהירות ובפשטות. נוסח הסכם הורות משותפת עורך דין אלעד כהן`,

    categoryHeb: 'משפחה',
    id: '2',
    price: 85,
    title: `הסכם הורות משותפת`,
    contractBody: ``,
  },
  {
    hasBasicColumn: true,
    hasMekifColumn: true,
    hasCustomColumn: true,
    hasMeetingColumn: true,

    numOfPagesBasic: '4',
    wordFileBasic: false,
    tailoredBasic: false,
    numOfFixesBasic: '0',
    makingTimeBasic: '0',
    levelOfProtectionBasic: '2',
    warrantyBasic: false,
    numOfPagesMekif: '10',
    wordFileMekif: true,
    tailoredMekif: false,
    numOfFixesMekif: '0',
    makingTimeMekif: '0',
    levelOfProtectionMekif: '3',
    warrantyMekif: false,
    priceMekif: '220',
    numOfPagesCustom: '11',
    wordFileCustom: true,
    tailoredCustom: true,
    numOfFixesCustom: '1',
    makingTimeCustom: '2',
    levelOfProtectionCustom: '4',
    warrantyCustom: false,
    priceCustom: '720',
    numOfPagesMeeting: '0',
    wordFileMeeting: true,
    tailoredMeeting: true,
    numOfFixesMeeting: '2',
    makingTimeMeeting: '7',
    levelOfProtectionMeeting: '5',
    warrantyMeeting: true,
    priceMeeting: '1320',
    imgSrc: '../assets/img/contracts/הסכם מייסדים.jpg',
    buttonText: 'פתח עוד',
    href: 'contract/3',
    h1: 'הסכם מייסדים',
    tags: ['הסכם מייסדים', 'הסכם מייסדים סטארט אפ', 'הסכם מייסדים בעלי מניות בחברה', 'הסכם מייסדים להקמת חברה'],

    seoHeader: `הסכם מייסדים לדוגמא - הסכם מייסדים לרכישה און ליין שירות חדש / עו"ד אלעד כהן`,
    seoDescription: `הסכם מייסדים - שאלות ותשובות בנושא הסכם מייסדים סטארט אפ - רכישת הסכם מייסדים מקיף און ליין במהירות ובפשטות. הסכם מייסדים להקמת חברה.`,

    categoryHeb: 'חברות וסטארט אפ',
    id: '3',
    price: 85,
    title: ` הסכם מייסדים`,
  },
  {
    hasBasicColumn: true,
    hasMekifColumn: true,
    hasCustomColumn: true,
    hasMeetingColumn: true,

    numOfPagesBasic: '3',
    wordFileBasic: false,
    tailoredBasic: false,
    numOfFixesBasic: '0',
    makingTimeBasic: '0',
    levelOfProtectionBasic: '2',
    warrantyBasic: false,
    numOfPagesMekif: '9',
    wordFileMekif: true,
    tailoredMekif: false,
    numOfFixesMekif: '0',
    makingTimeMekif: '0',
    levelOfProtectionMekif: '3',
    warrantyMekif: false,
    priceMekif: '220',
    numOfPagesCustom: '10',
    wordFileCustom: true,
    tailoredCustom: true,
    numOfFixesCustom: '1',
    makingTimeCustom: '2',
    levelOfProtectionCustom: '4',
    warrantyCustom: false,
    priceCustom: '720',
    numOfPagesMeeting: '0',
    wordFileMeeting: true,
    tailoredMeeting: true,
    numOfFixesMeeting: '2',
    makingTimeMeeting: '7',
    levelOfProtectionMeeting: '5',
    warrantyMeeting: true,
    priceMeeting: '1320',
    imgSrc: '../assets/img/contracts/הסכם מכר.jpg',
    buttonText: 'פתח עוד',
    href: '/contract/4',
    h1: 'הסכם מכר',
    tags: ['עורך דין מקרקעין', ' עורך דין נדלן', 'הסכם מכר דירה', 'חוזה מכר'],

    seoHeader: `הסכם מכר לדוגמא - הסכם מכר לרכישה און ליין שירות חדש / עו"ד אלעד כהן
    `,
    seoDescription: `הסכם מכר דירה - שאלות ותשובות בנושא הסכם מכר - רכישת הסכם מכר דירה מקיף און ליין במהירות ובפשטות. עורך דין מקרקעין אלעד כהן.`,

    categoryHeb: 'מקרקעין',
    id: '4',
    price: 85,
    title: `הסכם מכר`,
  },
  {
    hasBasicColumn: true,
    hasMekifColumn: true,
    hasCustomColumn: true,
    hasMeetingColumn: true,
    numOfPagesBasic: '4',
    wordFileBasic: false,
    tailoredBasic: false,
    numOfFixesBasic: '0',
    makingTimeBasic: '0',
    levelOfProtectionBasic: '2',
    warrantyBasic: false,
    numOfPagesMekif: '11',
    wordFileMekif: true,
    tailoredMekif: false,
    numOfFixesMekif: '0',
    makingTimeMekif: '0',
    levelOfProtectionMekif: '3',
    warrantyMekif: false,
    priceMekif: '220',
    numOfPagesCustom: '12',
    wordFileCustom: true,
    tailoredCustom: true,
    numOfFixesCustom: '1',
    makingTimeCustom: '2',
    levelOfProtectionCustom: '4',
    warrantyCustom: false,
    priceCustom: '720',
    numOfPagesMeeting: '0',
    wordFileMeeting: true,
    tailoredMeeting: true,
    numOfFixesMeeting: '2',
    makingTimeMeeting: '7',
    levelOfProtectionMeeting: '5',
    warrantyMeeting: true,
    priceMeeting: '1320',
    seoHeader: `ידועים בציבור - מידע מקיף וייעוץ ראשוני / רכישת הסכם און ליין / עו"ד אלעד כהן`,
    seoDescription: `חיים משותפים - רכישת הסכם חיים משותפים ידועים בציבור מקיף במהירות ובפשטות און ליין - ידועים בציבור עורך דין`,
    imgSrc: '../assets/img/contracts/הסכם ידועים בציבור.jpg',
    buttonText: 'פתח עוד',
    href: 'contract/5',
    h1: 'הסכם  ממון ידועים בציבור',
    tags: ['הסכם  ממון ידועים בציבור', 'הסכם ממון לפני נישואין', 'עורך דין הסכם ממון', 'הסכם ממון דוגמא'],

    seoHeader: `הסכם ממון לדוגמא - הסכם ממון לרכישה און ליין שירות חדש / עו"ד אלעד כהן
    `,
    seoDescription: 'הסכם ממון - שאלות ותשובות בנושא הסכם ממון - רכישת הסכם ממון מקיף און ליין במהירות ובפשטות. עורך דין הסכם ממון אלעד כהן',

    categoryHeb: 'משפחה',
    id: '5',
    price: 85,
    title: 'הסכם  ממון ידועים בציבור',
  },
  {
    hasBasicColumn: true,
    hasMekifColumn: true,
    hasCustomColumn: true,
    hasMeetingColumn: true,

    numOfPagesBasic: '2',
    wordFileBasic: false,
    tailoredBasic: false,
    numOfFixesBasic: '0',
    makingTimeBasic: '0',
    levelOfProtectionBasic: '2',
    warrantyBasic: false,
    numOfPagesMekif: '5',
    wordFileMekif: true,
    tailoredMekif: false,
    numOfFixesMekif: '0',
    makingTimeMekif: '0',
    levelOfProtectionMekif: '3',
    warrantyMekif: false,
    priceMekif: '120',
    numOfPagesCustom: '6',
    wordFileCustom: true,
    tailoredCustom: true,
    numOfFixesCustom: '1',
    makingTimeCustom: '2',
    levelOfProtectionCustom: '4',
    warrantyCustom: false,
    priceCustom: '520',
    numOfPagesMeeting: '0',
    wordFileMeeting: true,
    tailoredMeeting: true,
    numOfFixesMeeting: '2',
    makingTimeMeeting: '7',
    levelOfProtectionMeeting: '5',
    warrantyMeeting: true,
    priceMeeting: '1120',
    imgSrc: '../assets/img/contracts/הסכם סודיות.jpg',
    buttonText: 'פתח עוד',
    href: 'contract/6',
    h1: 'הסכם סודיות',
    tags: ['הסכם סודיות', 'הסכם סודיות דוגמא', 'הסכם סודיות הדדי', ' חוזה סודיות', 'הסכם סודיות סטארט אפ'],

    seoHeader: ``,
    seoDescription: `עו"ד אלעד כהן`,

    categoryHeb: 'כללי',
    id: '6',
    price: 85,
    title: `הסכם סודיות`,
  },
  {
    hasBasicColumn: true,
    hasMekifColumn: true,
    hasCustomColumn: true,
    hasMeetingColumn: true,

    numOfPagesBasic: '4',
    wordFileBasic: false,
    tailoredBasic: false,
    numOfFixesBasic: '0',
    makingTimeBasic: '0',
    levelOfProtectionBasic: '2',
    warrantyBasic: false,
    numOfPagesMekif: '13',
    wordFileMekif: true,
    tailoredMekif: false,
    numOfFixesMekif: '0',
    makingTimeMekif: '0',
    levelOfProtectionMekif: '3',
    warrantyMekif: false,
    priceMekif: '320',
    numOfPagesCustom: '14',
    wordFileCustom: true,
    tailoredCustom: true,
    numOfFixesCustom: '1',
    makingTimeCustom: '2',
    levelOfProtectionCustom: '4',
    warrantyCustom: false,
    priceCustom: '820',
    numOfPagesMeeting: '0',
    wordFileMeeting: true,
    tailoredMeeting: true,
    numOfFixesMeeting: '2',
    makingTimeMeeting: '7',
    levelOfProtectionMeeting: '5',
    warrantyMeeting: true,
    priceMeeting: '1520',
    imgSrc: '../assets/img/contracts/הסכם עבודה עם קבלן.jpg',
    buttonText: 'פתח עוד',
    href: 'contract/7',
    h1: 'הסכם עבודה עם קבלן',
    tags: ['הסכם עבודה עם קבלן שיפוצים', 'הסכם עבודה עם קבלן שיפוצים דוגמא', 'הסכם  שיפוץ דירה'],

    seoHeader: `הסכם עבודה עם קבלן לדוגמא - הסכם לרכישה און ליין שירות חדש  / עו"ד אלעד כהן`,
    seoDescription: `הסכם עבודה עם קבלן - שאלות ותשובות בנושא הסכם עבודה עם קבלן שיפוצים - רכישת הסכם עבודה עם קבלן מקיף און ליין במהירות ובפשטות. הסכם שיפוץ דירה`,

    categoryHeb: 'כללי',
    id: '7',
    price: 85,
    title: `הסכם עבודה עם קבלן`,
  },
  {
    hasBasicColumn: true,
    hasMekifColumn: true,
    hasCustomColumn: true,
    hasMeetingColumn: true,

    numOfPagesBasic: '4',
    wordFileBasic: false,
    tailoredBasic: false,
    numOfFixesBasic: '0',
    makingTimeBasic: '0',
    levelOfProtectionBasic: '2',
    warrantyBasic: false,
    numOfPagesMekif: '9',
    wordFileMekif: true,
    tailoredMekif: false,
    numOfFixesMekif: '0',
    makingTimeMekif: '0',
    levelOfProtectionMekif: '3',
    warrantyMekif: false,
    priceMekif: '220',
    numOfPagesCustom: '10',
    wordFileCustom: true,
    tailoredCustom: true,
    numOfFixesCustom: '1',
    makingTimeCustom: '2',
    levelOfProtectionCustom: '4',
    warrantyCustom: false,
    priceCustom: '720',
    numOfPagesMeeting: '0',
    wordFileMeeting: true,
    tailoredMeeting: true,
    numOfFixesMeeting: '2',
    makingTimeMeeting: '7',
    levelOfProtectionMeeting: '5',
    warrantyMeeting: true,
    priceMeeting: '1320',
    imgSrc: '../assets/img/contracts/הסכם שותפות.jpg',
    buttonText: 'פתח עוד',
    href: 'contract/8',
    h1: 'הסכם שותפות',
    tags: ['הסכם שותפות', 'הסכם שותפות דוגמא', 'הסכם שותפות פשוט', ' חוזה שותפות', 'הסכם שותפות בעסק', 'הסכם שותפות עוסק מורשה'],

    seoHeader: `הסכם שותפות דוגמא - הסכם שותפות לרכישה און ליין שירות חדש / עו"ד אלעד כהן`,
    seoDescription: `הסכם שותפות  - שאלות ותשובות בנושא הסכם שותפות בעסק - רכישת הסכם שותפות מקיף און ליין במהירות ובפשטות. עורך דין הסכם שותפות עוסק מורשה`,

    categoryHeb: 'חברות וסטארט אפ',
    id: '8',
    price: 85,
    title: `הסכם שותפות`,
  },
  {
    hasBasicColumn: true,
    hasMekifColumn: true,
    hasCustomColumn: true,
    hasMeetingColumn: true,

    numOfPagesBasic: '3',
    wordFileBasic: false,
    tailoredBasic: false,
    numOfFixesBasic: '0',
    makingTimeBasic: '0',
    levelOfProtectionBasic: '2',
    warrantyBasic: false,
    numOfPagesMekif: '8',
    wordFileMekif: true,
    tailoredMekif: false,
    numOfFixesMekif: '0',
    makingTimeMekif: '0',
    levelOfProtectionMekif: '3',
    warrantyMekif: false,
    priceMekif: '220',
    numOfPagesCustom: '9',
    wordFileCustom: true,
    tailoredCustom: true,
    numOfFixesCustom: '1',
    makingTimeCustom: '2',
    levelOfProtectionCustom: '4',
    warrantyCustom: false,
    priceCustom: '720',
    numOfPagesMeeting: '0',
    wordFileMeeting: true,
    tailoredMeeting: true,
    numOfFixesMeeting: '2',
    makingTimeMeeting: '7',
    levelOfProtectionMeeting: '5',
    warrantyMeeting: true,
    priceMeeting: '1320',
    imgSrc: '../assets/img/contracts/הסכם שיתוף במקרקעין.jpg',
    buttonText: 'פתח עוד',
    href: 'contract/9',
    h1: 'הסכם שיתוף במקרקעין',
    tags: ['הסכם שיתוף במקרקעין', 'הסכם שיתוף במקרקעין דוגמא', 'הסכם שיתוף במקרקעין דו משפחתי', 'דוגמת הסכם שיתוף במקרקעין'],

    seoHeader: `הסכם שיתוף במקרקעין דוגמא - הסכם לרכישה און ליין שירות חדש  / עו"ד אלעד כהן`,
    seoDescription: `הסכם שיתוף במקרקעין - שאלות ותשובות בנושא הסכם שיתוף במקרקעין - רכישת הסכם שיתוף במקרקעין דו משפחתי מקיף און ליין במהירות ובפשטות.`,

    categoryHeb: 'מקרקעין',
    id: '9',
    price: 85,
    title: `הסכם שיתוף במקרקעין`,
  },
  {
    hasBasicColumn: true,
    hasMekifColumn: true,
    hasCustomColumn: true,
    hasMeetingColumn: true,

    numOfPagesBasic: '3',
    wordFileBasic: false,
    tailoredBasic: false,
    numOfFixesBasic: '0',
    makingTimeBasic: '0',
    levelOfProtectionBasic: '2',
    warrantyBasic: false,
    numOfPagesMekif: '7',
    wordFileMekif: true,
    tailoredMekif: false,
    numOfFixesMekif: '0',
    makingTimeMekif: '0',
    levelOfProtectionMekif: '3',
    warrantyMekif: false,
    priceMekif: '220',
    numOfPagesCustom: '8',
    wordFileCustom: true,
    tailoredCustom: true,
    numOfFixesCustom: '1',
    makingTimeCustom: '2',
    levelOfProtectionCustom: '4',
    warrantyCustom: false,
    priceCustom: '720',
    numOfPagesMeeting: '0',
    wordFileMeeting: true,
    tailoredMeeting: true,
    numOfFixesMeeting: '2',
    makingTimeMeeting: '7',
    levelOfProtectionMeeting: '5',
    warrantyMeeting: true,
    priceMeeting: '1320',
    imgSrc: '../assets/img/contracts/חוזה עבודה.jpg',
    buttonText: 'פתח עוד',
    href: 'contract/10',
    h1: 'חוזה עבודה',
    tags: ['חוזה עבודה אישי', 'חוזה עבודה סטנדרטי', 'חוזה העסקה'],

    seoHeader: `חוזה עבודה לדוגמא - חוזה עבודה לרכישה און ליין שירות חדש / עו"ד אלעד כהן`,
    seoDescription: `חוזה עבודה - שאלות ותשובות בנושא חוזה עבודה אישי - רכישת חוזה עבודה מקיף און ליין במהירות ובפשטות. עורך דין חוזה עבודה אלעד כהן.`,

    categoryHeb: 'עבודה',
    id: '10',
    price: 85,
    title: `חוזה עבודה`,
  },
  {
    hasBasicColumn: false,
    hasMekifColumn: false,
    hasCustomColumn: false,
    hasMeetingColumn: true,

    numOfPagesBasic: '3',
    wordFileBasic: false,
    tailoredBasic: false,
    numOfFixesBasic: '0',
    makingTimeBasic: '0',
    levelOfProtectionBasic: '2',
    warrantyBasic: false,
    numOfPagesMekif: '12',
    wordFileMekif: true,
    tailoredMekif: false,
    numOfFixesMekif: '0',
    makingTimeMekif: '0',
    levelOfProtectionMekif: '3',
    warrantyMekif: false,
    priceMekif: '220',
    numOfPagesCustom: '13',
    wordFileCustom: true,
    tailoredCustom: true,
    numOfFixesCustom: '1',
    makingTimeCustom: '2',
    levelOfProtectionCustom: '4',
    warrantyCustom: false,
    priceCustom: '720',
    numOfPagesMeeting: '0',
    wordFileMeeting: true,
    tailoredMeeting: true,
    numOfFixesMeeting: '2',
    makingTimeMeeting: '7',
    levelOfProtectionMeeting: '5',
    warrantyMeeting: true,
    priceMeeting: '1320',
    imgSrc: '../assets/img/contracts/יפוי כח מתמשך.jpg',
    buttonText: 'פתח עוד',
    href: 'contract/11',
    h1: 'יפוי כח מתמשך',
    tags: ['הסכם שותפות', 'הסכם שותפות דוגמא', 'הסכם שותפות פשוט', ' חוזה שותפות', 'הסכם שותפות בעסק', 'הסכם שותפות עוסק מורשה'],

    seoHeader: `ייפוי כוח מתמשך לדוגמא - ייפוי כוח מתמשך שירות חדש / עו"ד אלעד כהן`,
    seoDescription: `ייפוי כוח מתמשך לדוגמא - שאלות ותשובות בנושא ייפוי כוח מתמשך - עורך דין ייפוי כוח מתמשך - עריכת יפוי כח מתמשך `,

    h2: 'יפוי כוח מתמשך',
    h3: 'עורך דין ייפוי כוח מתמשך',
    h4: 'עריכת יפוי כח מתמשך',
    categoryHeb: 'כללי',
    id: '11',
    price: 85,
    title: `יפוי כח מתמשך`,
  },
];

module.exports = previewContract;
