export const allProdcts = [
  { title: "prodcts",href:"/contractpage",cost:"350" ,buttonText: "פתח חוזה לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/contractpage",cost:"350" ,buttonText: "פתח חוזה לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/contractpage",cost:"350" ,buttonText: "פתח חוזה לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/contractpage",cost:"350" ,buttonText: "פתח חוזה לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/contractpage",cost:"350" ,buttonText: "פתח חוזה לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/contractpage",cost:"350" ,buttonText: "פתח חוזה לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/contractpage",cost:"350" ,buttonText: "פתח חוזה לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/contractpage",cost:"350" ,buttonText: "פתח חוזה לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/contractpage",cost:"350" ,buttonText: "פתח חוזה לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/contractpage",cost:"350" ,buttonText: "פתח חוזה לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/contractpage",cost:"350" ,buttonText: "פתח חוזה לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/contractpage",cost:"350" ,buttonText: "פתח חוזה לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/contractpage",cost:"350" ,buttonText: "פתח חוזה לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
];
export const allServices = [
  { title: "prodcts",href:"/officeservice",cost:"350" ,buttonText: "פתח שירות לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/officeservice",cost:"350" ,buttonText: "פתח שירות לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/officeservice",cost:"350" ,buttonText: "פתח שירות לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/officeservice",cost:"350" ,buttonText: "פתח שירות לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/officeservice",cost:"350" ,buttonText: "פתח שירות לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/officeservice",cost:"350" ,buttonText: "פתח שירות לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/officeservice",cost:"350" ,buttonText: "פתח שירות לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/officeservice",cost:"350" ,buttonText: "פתח שירות לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/officeservice",cost:"350" ,buttonText: "פתח שירות לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/officeservice",cost:"350" ,buttonText: "פתח שירות לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/officeservice",cost:"350" ,buttonText: "פתח שירות לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/officeservice",cost:"350" ,buttonText: "פתח שירות לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  { title: "prodcts",href:"/officeservice",cost:"350" ,buttonText: "פתח שירות לדוגמא", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
];
