export const allProdcts = [
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  ];
  export const allServices = [
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
    { title: "prodcts", description: "testtesttesttesttesttesttesttesttesttesttesttest" },
  ];